### ISSUE TITLE
Enhance the UX for the Tabs

### ISSUE THREAD

**Issue by grebaldi** [PackageFactory/PackageFactory.Guevara#11]
This might be of help, when used in the guest frame:

```js
window.onbeforeunload = (e) => {
    console.log(document.activeElement.href);
};
```

**Comment by Inkdpixels** [comment]
Handling the singleton approach for Tabs ist one aspect, we should also make the drag & drop feature more user friendly by displaying the draggable area once the user starts to drag an anchor. At that point we also need to validate the item being dragged, since some links shouldn't be droppable in the BottomBar Container.

**Comment by grebaldi** [comment]
Will close this, since the tab feature is dropped.
